logstash:
  extends:
    file: ../docker/common.yml
    service: logstash
  links:
  - elastic

mongodb:
  extends:
    file: ../docker/common.yml
    service: mongodb

redis:
  extends:
    file: ../docker/common.yml
    service: redis

kibana:
  extends:
    file: ../docker/common.yml
    service: kibana
  links:
  - elastic

elastic:
  extends:
    file: ../docker/common.yml
    service: elastic

postfix:
  extends:
    file: ../docker/common.yml
    service: postfix

backend:
  extends:
    file: ../docker/common.yml
    service: backend
  links:
    - mongodb
    - redis
    - elastic
    - logstash
    - postfix
  environment:
    - SUPERDESK_URL=http://localhost:5000/api
    - SUPERDESK_CLIENT_URL=http://localhost:5000
    - SUPERDESK_TESTING=True
  ports:
    - "5000:5000"
    - "5100:5100"
