mongodb:
  image: library/mongo
  # volumes:
  #  - ../data/mongodb:/data/db

redis:
  image: library/redis
  # volumes:
  #  - ../data/redis:/data

elastic:
  image: library/elasticsearch
  # volumes:
  #  - ../data/elastic:/data

backend:
  build: .
  command: sh /opt/superdesk/scripts/fig_wrapper.sh honcho start
  links:
   - mongodb
   - redis
   - elastic
  ports:
   - "5000:5000"
   - "5100:5100"
  environment:
   - MONGOLAB_URI=mongodb://mongodb:27017/test
   - LEGAL_ARCHIVEDB_PORT=mongodb://mongodb:27017
   - ELASTICSEARCH_URL=http://elastic:9200
   - ELASTICSEARCH_INDEX
   - CELERY_BROKER_URL=redis://redis:6379/1
   - REDIS_URL=redis://redis:6379/1
   - AMAZON_ACCESS_KEY_ID
   - AMAZON_CONTAINER_NAME=liveblog-dev
   - AMAZON_REGION
   - AMAZON_SECRET_ACCESS_KEY
   - REUTERS_USERNAME
   - REUTERS_PASSWORD
   - MAIL_SERVER
   - MAIL_PORT
   - MAIL_USE_TLS
   - MAIL_USE_SSL
   - MAIL_USERNAME
   - MAIL_PASSWORD
   - SENTRY_DSN
   - SUPERDESK_URL=http://localhost:5000/api
   - SUPERDESK_CLIENT_URL=http://localhost:5000
   - SUPERDESK_TESTING=True
  volumes:
   - .:/opt/superdesk
