import 'lb-bootstrap.less';

import 'jquery-ui/jquery-ui';
import 'bootstrap';
import 'angular';
import 'angular-bootstrap-npm';
import 'angular-resource';
import 'angular-route';
import 'ng-file-upload';
import 'angular-gettext';
import 'angular-vs-repeat';
import 'angular-embedly';
import 'angular-embed/dist/angular-embed';
import 'angular-contenteditable';
import 'angular-messages';
import 'lodash';
import 'lr-infinite-scroll';
import 'ment.io';

//import 'superdesk-core/styles/less/bootstrap.less';

// core
import 'superdesk-core/scripts/superdesk/gettext';
import 'superdesk-core/scripts/superdesk/activity';
import 'superdesk-core/scripts/superdesk/analytics';
import 'superdesk-core/scripts/superdesk/api';
import 'superdesk-core/scripts/superdesk/auth';
import 'superdesk-core/scripts/superdesk/beta';
import 'superdesk-core/scripts/superdesk/datetime';
import 'superdesk-core/scripts/superdesk/error';
import 'superdesk-core/scripts/superdesk/elastic';
import 'superdesk-core/scripts/superdesk/filters';
import 'superdesk-core/scripts/superdesk/services';
import 'superdesk-core/scripts/superdesk/directives';
import 'superdesk-core/scripts/superdesk/editor/editor';
import 'superdesk-core/scripts/superdesk/editor/spellcheck/spellcheck';
import 'superdesk-core/scripts/superdesk/features';
import 'superdesk-core/scripts/superdesk/list';
import 'superdesk-core/scripts/superdesk/keyboard';
import 'superdesk-core/scripts/superdesk/privileges';
import 'superdesk-core/scripts/superdesk/notification';
import 'superdesk-core/scripts/superdesk/itemList';
import 'superdesk-core/scripts/superdesk/menu';
import 'superdesk-core/scripts/superdesk/notify';
import 'superdesk-core/scripts/superdesk/ui';
import 'superdesk-core/scripts/superdesk/upload';
import 'superdesk-core/scripts/superdesk/lang';
import 'superdesk-core/scripts/superdesk/superdesk';

import 'superdesk-core/scripts/superdesk-workspace';
import 'superdesk-core/scripts/superdesk-dashboard';
import 'superdesk-core/scripts/superdesk-users';
import 'superdesk-core/scripts/superdesk-groups';
import 'superdesk-core/scripts/superdesk-products';
import 'superdesk-core/scripts/superdesk-publish';
import 'superdesk-core/scripts/superdesk-templates';
import 'superdesk-core/scripts/superdesk-profiling';
import 'superdesk-core/scripts/superdesk-desks';
import 'superdesk-core/scripts/superdesk-authoring';
import 'superdesk-core/scripts/superdesk-search';
import 'superdesk-core/scripts/superdesk-legal-archive';
import 'superdesk-core/scripts/superdesk-stream';
import 'superdesk-core/scripts/superdesk-packaging';
import 'superdesk-core/scripts/superdesk-highlights';
import 'superdesk-core/scripts/superdesk-content-filters';
import 'superdesk-core/scripts/superdesk-dictionaries';
import 'superdesk-core/scripts/superdesk-vocabularies';
import 'superdesk-core/scripts/superdesk-archive';
import 'superdesk-core/scripts/superdesk/editor/spellcheck/spellcheck';
import 'superdesk-core/scripts/superdesk-monitoring';
import 'superdesk-core/scripts/superdesk-settings';
import 'superdesk-core/scripts/superdesk-ingest';
import 'superdesk-core/scripts/superdesk-search-providers';

import 'liveblog-bloglist';
import 'liveblog-edit';
import 'liveblog-themes';

//import 'liveblog-bloglist/module';
//import 'liveblog-edit/module';
//import 'liveblog-edit/directives';
//import 'liveblog-edit/posts.service';
//import 'liveblog-edit/unread.posts.service';
import 'liveblog-security.service';
//import 'liveblog-themes/module'
//import 'liveblog-themes/themes.services'

import './ng-sir-trevor';
import './lb-templates';
import './lb-bootstrap';
