dist: trusty

language: python

sudo: required

python:
  - "3.5"

env:
  global:
    - CXX=g++-4.8
    - NODE_ENV=development

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - openjdk-7-jdk

before_install:
  - sudo apt-get -y install python3-pip python3-dev

install:
  - nvm install --lts node
  - nvm use node
  - node --version
  - npm install -g gulp
  - npm install
  
script:
  - gulp lint
  - gulp
